[general]
import = ["~/.config/alacritty/themes/hyper.toml"]

[font]
size = 16.0

[font.normal]
family = "JetBrainsMonoNL NF"
style = "Regular"

[font.bold]
family = "JetBrainsMonoNL NF"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL NF"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMonoNL NF"
style = "Bold Italic"
